package com.shah.chainsupershop.domain;
// Generated Jul 20, 2018 9:29:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name="branch"
    ,catalog="chain_super_shop"
)
public class Branch  implements java.io.Serializable {


     private Integer branchRegId;
     private User user;
     private String branchName;
     private String branchLocation;
     private Set<Accept> accepts = new HashSet<Accept>(0);
     private Set<Sales> saleses = new HashSet<Sales>(0);
     private Set<Distribution> distributions = new HashSet<Distribution>(0);

    public Branch() {
    }

	
    public Branch(User user, String branchName, String branchLocation) {
        this.user = user;
        this.branchName = branchName;
        this.branchLocation = branchLocation;
    }
    public Branch(User user, String branchName, String branchLocation, Set<Accept> accepts, Set<Sales> saleses, Set<Distribution> distributions) {
       this.user = user;
       this.branchName = branchName;
       this.branchLocation = branchLocation;
       this.accepts = accepts;
       this.saleses = saleses;
       this.distributions = distributions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="branch_reg_id", unique=true, nullable=false)
    public Integer getBranchRegId() {
        return this.branchRegId;
    }
    
    public void setBranchRegId(Integer branchRegId) {
        this.branchRegId = branchRegId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="branch_name", nullable=false, length=45)
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    
    @Column(name="branch_location", nullable=false, length=45)
    public String getBranchLocation() {
        return this.branchLocation;
    }
    
    public void setBranchLocation(String branchLocation) {
        this.branchLocation = branchLocation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="branch")
    public Set<Accept> getAccepts() {
        return this.accepts;
    }
    
    public void setAccepts(Set<Accept> accepts) {
        this.accepts = accepts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="branch")
    public Set<Sales> getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set<Sales> saleses) {
        this.saleses = saleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="branch")
    public Set<Distribution> getDistributions() {
        return this.distributions;
    }
    
    public void setDistributions(Set<Distribution> distributions) {
        this.distributions = distributions;
    }




}


