package com.shah.chainsupershop.domain;
// Generated Jul 20, 2018 9:29:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Distribution generated by hbm2java
 */
@Entity
@Table(name="distribution"
    ,catalog="chain_super_shop"
)
public class Distribution  implements java.io.Serializable {


     private Integer distId;
     private Branch branch;
     private Category category;
     private Product product;
     private SubCategory subCategory;
     private Date distDate;
     private String distStatus;
     private int distQty;
     private double totalAmount;

    public Distribution() {
    }

    public Distribution(Branch branch, Category category, Product product, SubCategory subCategory, Date distDate, String distStatus, int distQty, double totalAmount) {
       this.branch = branch;
       this.category = category;
       this.product = product;
       this.subCategory = subCategory;
       this.distDate = distDate;
       this.distStatus = distStatus;
       this.distQty = distQty;
       this.totalAmount = totalAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dist_id", unique=true, nullable=false)
    public Integer getDistId() {
        return this.distId;
    }
    
    public void setDistId(Integer distId) {
        this.distId = distId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="branch_reg_id", nullable=false)
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_cat_id", nullable=false)
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dist_date", nullable=false, length=10)
    public Date getDistDate() {
        return this.distDate;
    }
    
    public void setDistDate(Date distDate) {
        this.distDate = distDate;
    }

    
    @Column(name="dist_status", nullable=false, length=45)
    public String getDistStatus() {
        return this.distStatus;
    }
    
    public void setDistStatus(String distStatus) {
        this.distStatus = distStatus;
    }

    
    @Column(name="dist_qty", nullable=false)
    public int getDistQty() {
        return this.distQty;
    }
    
    public void setDistQty(int distQty) {
        this.distQty = distQty;
    }

    
    @Column(name="total_amount", nullable=false, precision=22, scale=0)
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }




}


