package com.shah.chainsupershop.domain;
// Generated Jul 20, 2018 9:29:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="chain_super_shop"
)
public class Product  implements java.io.Serializable {


     private Integer productId;
     private Category category;
     private SubCategory subCategory;
     private String productName;
     private double productPrice;
     private int productQty;
     private String productDesc;
     private String imgPath;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);
     private Set<Distribution> distributions = new HashSet<Distribution>(0);
     private Set<Accept> accepts = new HashSet<Accept>(0);

    public Product() {
    }

	
    public Product(Category category, SubCategory subCategory, String productName, double productPrice, int productQty, String productDesc) {
        this.category = category;
        this.subCategory = subCategory;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productQty = productQty;
        this.productDesc = productDesc;
    }
    public Product(Category category, SubCategory subCategory, String productName, double productPrice, int productQty, String productDesc, String imgPath, Set<Purchase> purchases, Set<Distribution> distributions, Set<Accept> accepts) {
       this.category = category;
       this.subCategory = subCategory;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productQty = productQty;
       this.productDesc = productDesc;
       this.imgPath = imgPath;
       this.purchases = purchases;
       this.distributions = distributions;
       this.accepts = accepts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_cat_id", nullable=false)
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_price", nullable=false, precision=22, scale=0)
    public double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }

    
    @Column(name="product_qty", nullable=false)
    public int getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(int productQty) {
        this.productQty = productQty;
    }

    
    @Column(name="product_desc", nullable=false, length=45)
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    
    @Column(name="img_path", length=45)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Distribution> getDistributions() {
        return this.distributions;
    }
    
    public void setDistributions(Set<Distribution> distributions) {
        this.distributions = distributions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Accept> getAccepts() {
        return this.accepts;
    }
    
    public void setAccepts(Set<Accept> accepts) {
        this.accepts = accepts;
    }




}


