package com.shah.chainsupershop.domain;
// Generated Jul 20, 2018 9:29:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name="sales"
    ,catalog="chain_super_shop"
)
public class Sales  implements java.io.Serializable {


     private Integer saleId;
     private Branch branch;
     private Customer customer;
     private Date saleDate;
     private double salePrice;
     private int saleQty;
     private String saleDesc;

    public Sales() {
    }

    public Sales(Branch branch, Customer customer, Date saleDate, double salePrice, int saleQty, String saleDesc) {
       this.branch = branch;
       this.customer = customer;
       this.saleDate = saleDate;
       this.salePrice = salePrice;
       this.saleQty = saleQty;
       this.saleDesc = saleDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sale_id", unique=true, nullable=false)
    public Integer getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="branch_reg_id", nullable=false)
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sale_date", nullable=false, length=10)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    
    @Column(name="sale_price", nullable=false, precision=22, scale=0)
    public double getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }

    
    @Column(name="sale_qty", nullable=false)
    public int getSaleQty() {
        return this.saleQty;
    }
    
    public void setSaleQty(int saleQty) {
        this.saleQty = saleQty;
    }

    
    @Column(name="sale_desc", nullable=false, length=45)
    public String getSaleDesc() {
        return this.saleDesc;
    }
    
    public void setSaleDesc(String saleDesc) {
        this.saleDesc = saleDesc;
    }




}


