package com.shah.chainsupershop.domain;
// Generated Jul 20, 2018 9:29:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name="sub_category"
    ,catalog="chain_super_shop"
)
public class SubCategory  implements java.io.Serializable {


     private Integer subCatId;
     private Category category;
     private String subCatName;
     private String subCatDesc;
     private String imgPath;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);
     private Set<Distribution> distributions = new HashSet<Distribution>(0);
     private Set<Accept> accepts = new HashSet<Accept>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public SubCategory() {
    }

	
    public SubCategory(Category category, String subCatName, String subCatDesc) {
        this.category = category;
        this.subCatName = subCatName;
        this.subCatDesc = subCatDesc;
    }
    public SubCategory(Category category, String subCatName, String subCatDesc, String imgPath, Set<Purchase> purchases, Set<Distribution> distributions, Set<Accept> accepts, Set<Product> products) {
       this.category = category;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.imgPath = imgPath;
       this.purchases = purchases;
       this.distributions = distributions;
       this.accepts = accepts;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_cat_id", unique=true, nullable=false)
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="sub_cat_name", nullable=false, length=45)
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }

    
    @Column(name="sub_cat_desc", nullable=false, length=45)
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }

    
    @Column(name="img_path", length=45)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Distribution> getDistributions() {
        return this.distributions;
    }
    
    public void setDistributions(Set<Distribution> distributions) {
        this.distributions = distributions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Accept> getAccepts() {
        return this.accepts;
    }
    
    public void setAccepts(Set<Accept> accepts) {
        this.accepts = accepts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


